# Generated by Django 3.0.6 on 2020-06-01 19:49

import assets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_display_name', models.CharField(max_length=255, verbose_name='name of venue')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_code', models.CharField(default=assets.models.Asset.get_default_invite_code, max_length=12, unique=True, verbose_name='invitation code to share with members')),
                ('invite_code_url', models.URLField(default=assets.models.Asset.get_default_invite_url, unique=True, verbose_name='link to share with members')),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='asset_images', verbose_name='venue_image')),
                ('is_activated', models.BooleanField(blank=True, default=False, verbose_name='is this venue activated?')),
                ('requires_member_verification', models.BooleanField(blank=True, default=False, verbose_name='venue requires member verification?')),
                ('asset_weekday_opening_time', models.TimeField(default='09:00', verbose_name='Opening Time on a Weekday')),
                ('asset_weekday_closing_time', models.TimeField(default='20:00', verbose_name='Closing Time on a Weekday')),
                ('asset_weekend_opening_time', models.TimeField(default='10:00', verbose_name='Opening Time on a Weekend')),
                ('asset_weekend_closing_time', models.TimeField(default='18:00', verbose_name='Closing Time on a Weekend')),
                ('asset_max_bookings', models.IntegerField(default=3, verbose_name='Member Booking Limit')),
            ],
        ),
        migrations.CreateModel(
            name='AssetOpeningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_opening_days', models.IntegerField(verbose_name='Business Days per Week')),
                ('asset_opening_days_desc', models.CharField(max_length=30, verbose_name='Day Groups')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSlotDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_slot_duration_mins', models.IntegerField(verbose_name='Booking Frequency')),
                ('asset_slot_duration_desc', models.CharField(max_length=30, verbose_name='Frequency Description')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=30, verbose_name='Venue Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_User_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(verbose_name='Venue Owner/Employee')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_membership_ID', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member ID')),
                ('is_activated', models.BooleanField(default=True, verbose_name='user_status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='user_verification_status')),
                ('invite_code_used', models.CharField(max_length=8, verbose_name='invitation code used')),
                ('asset_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_asset_asset', to='assets.Asset')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_OpenDays_Exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateField(verbose_name='exception date')),
                ('asset_opening_time_exception', models.TimeField(default='09:00', verbose_name='Opening Time')),
                ('asset_closing_time_exception', models.TimeField(default='20:00', verbose_name='Closing Time')),
                ('asset_max_bookings', models.IntegerField(default=3, verbose_name='Member Booking Limit')),
                ('asset_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_asset', to='assets.Asset')),
                ('asset_slot_duration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetSlotDuration', verbose_name='Booking Slot Duration (Minutes)')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_opening_days',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetOpeningDay', verbose_name='Days Open per Week'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_slot_duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetSlotDuration', verbose_name='Booking Slot Duration (Minutes)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType', verbose_name='type of venue'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_users',
            field=models.ManyToManyField(through='assets.Asset_User_Mapping', to=settings.AUTH_USER_MODEL, verbose_name='list of members'),
        ),
        migrations.AddConstraint(
            model_name='asset_opendays_exception',
            constraint=models.UniqueConstraint(fields=('the_date', 'asset_ID'), name='unique exception'),
        ),
    ]
