# Generated by Django 3.0.6 on 2020-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='num_days_display_to_users',
            field=models.IntegerField(default=30, verbose_name='future days bookings allowed'),
        ),
        migrations.AlterField(
            model_name='asset_user_mapping',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='user is activated?'),
        ),
        migrations.AlterField(
            model_name='asset_user_mapping',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is user verified?'),
        ),
    ]
