# Generated by Django 3.0.6 on 2020-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200604_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_opendays_exception',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Venue is not open'),
        ),
    ]
