# Generated by Django 3.0.6 on 2020-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_opendays_exception_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_user_mapping',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Office Notes'),
        ),
        migrations.AddField(
            model_name='asset_user_mapping',
            name='asset_swipt_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Swipe ID'),
        ),
        migrations.AlterField(
            model_name='asset_opendays_exception',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Venue is closed'),
        ),
    ]
