# Generated by Django 3.0.6 on 2020-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200609_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_user_mapping',
            old_name='asset_swipt_ID',
            new_name='asset_swipe_ID',
        ),
        migrations.AlterField(
            model_name='asset',
            name='invite_code',
            field=models.CharField(default=0, max_length=12, unique=True, verbose_name='invitation code to share with members'),
        ),
        migrations.AlterField(
            model_name='asset_user_mapping',
            name='invite_code_used',
            field=models.CharField(max_length=12, verbose_name='invitation code used'),
        ),
    ]
